development:
  adapter: postgresql
  encoding: unicode
  database: presimondo_development
  pool: 5
  username: presimondo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: presimondo_test
  pool: 5
  username: presimondo
  password:
