development:
  adapter: postgresql
  encoding: unicode
  database: koncertowka_development
  pool: 5
  username: koncertowka
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: koncertowka_test
  pool: 5
  username: koncertowka
  password:
